"""Elementos reutilizables de interfaz."""

from comun.ui.contenedor_apilado import ContenedorApiladoAjustable
from comun.ui.componentes import (
    BotonAccionContextual,
    CampoDetalleSigqua,
    CampoBusquedaSeleccionSigqua,
    CampoMontoMonetario,
    EncabezadoDetalleSigqua,
    DialogoBaseSigqua,
    DialogoConfirmacionSigqua,
    DialogoMensajeSigqua,
    SeccionDetalleSigqua,
    ContenedorTarjetasResumenOperativo,
    TarjetaKPI,
    TarjetaResumenOperativa,
    TarjetaResumenDetalleSigqua,
    VistaPlaceholderModulo,
    aplicar_estilo_boton_operativo,
    configurar_tabla_operativa,
    crear_badge_estado_detalle_sigqua,
    crear_boton_copiar_detalle_sigqua,
    crear_boton_operativo,
    crear_item_tabla,
    obtener_estilo_detalle_sigqua,
    resolver_variante_boton_modal,
)
from comun.ui.documentos_pdf import (
    describir_estado_automatizacion_documental,
    ejecutar_acciones_documento_pdf,
)
from comun.ui.iconos import (
    obtener_icono_tabler,
    obtener_icono_tabler_coloreado,
    obtener_pixmap_marca,
    obtener_pixmap_tabler_coloreado,
)

__all__ = [
    "ContenedorApiladoAjustable",
    "BotonAccionContextual",
    "CampoDetalleSigqua",
    "CampoBusquedaSeleccionSigqua",
    "CampoMontoMonetario",
    "DialogoBaseSigqua",
    "DialogoConfirmacionSigqua",
    "DialogoMensajeSigqua",
    "EncabezadoDetalleSigqua",
    "SeccionDetalleSigqua",
    "ContenedorTarjetasResumenOperativo",
    "TarjetaKPI",
    "TarjetaResumenOperativa",
    "TarjetaResumenDetalleSigqua",
    "VistaPlaceholderModulo",
    "aplicar_estilo_boton_operativo",
    "configurar_tabla_operativa",
    "crear_badge_estado_detalle_sigqua",
    "crear_boton_copiar_detalle_sigqua",
    "crear_boton_operativo",
    "crear_item_tabla",
    "obtener_estilo_detalle_sigqua",
    "resolver_variante_boton_modal",
    "describir_estado_automatizacion_documental",
    "ejecutar_acciones_documento_pdf",
    "obtener_icono_tabler",
    "obtener_icono_tabler_coloreado",
    "obtener_pixmap_marca",
    "obtener_pixmap_tabler_coloreado",
]
